use customer_behavior;

-- select * from customer_shopping_behavior limit 20;

SHOW COLUMNS FROM customer_shopping_behavior;

-- Q1. What is the total revenue generated by male vs. female customers?

-- SELECT
--     Gender,
--     SUM(`Purchase Amount (USD)`) AS revenue
-- FROM customer_shopping_behavior
-- GROUP BY Gender;
-- Q2. Which customers used a discount but still spent more than the average purchase amount?

-- SELECT
--     `ï»¿Customer ID`,
--     `Purchase Amount (USD)`
-- FROM customer_shopping_behavior
-- WHERE `Discount Applied` = 'Yes'
--   AND `Purchase Amount (USD)` > (
--       SELECT AVG(`Purchase Amount (USD)`)
--       FROM customer_shopping_behavior
--   );
  
-- Q3. What are the top 5 products with the highest average review rating?

-- SELECT
--     `Item Purchased`,
--     AVG(`Review Rating`) AS average_review_rating
-- FROM customer_shopping_behavior
-- GROUP BY `Item Purchased`
-- ORDER BY average_review_rating DESC
-- LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

-- SELECT
--     `Shipping Type`,
--     AVG(`Purchase Amount (USD)`) AS average_purchase_amount
-- FROM customer_shopping_behavior
-- WHERE `Shipping Type` IN ('Standard', 'Express')
-- GROUP BY `Shipping Type`;

-- Q5. Do subscriber customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

-- SELECT
--     `Subscription Status`,
--     AVG(`Purchase Amount (USD)`) AS average_spend,
--     SUM(`Purchase Amount (USD)`) AS total_revenue
-- FROM customer_shopping_behavior
-- GROUP BY `Subscription Status`;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

-- SELECT
--     `Item Purchased`,
--     COUNT(*) AS total_purchases,
--     SUM(CASE
--             WHEN `Discount Applied` = 'Yes' THEN 1
--             ELSE 0
--         END) AS discounted_purchases,
--     ROUND(
--         (SUM(CASE
--                 WHEN `Discount Applied` = 'Yes' THEN 1
--                 ELSE 0
--              END) * 100.0) / COUNT(*),
--         2
--     ) AS discount_percentage
-- FROM customer_shopping_behavior
-- GROUP BY `Item Purchased`
-- ORDER BY discount_percentage DESC
-- LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

-- SELECT
--     CASE
--         WHEN `Previous Purchases` = 0 THEN 'New'
--         WHEN `Previous Purchases` BETWEEN 1 AND 10 THEN 'Returning'
--         ELSE 'Loyal'
--     END AS customer_segment,
--     COUNT(*) AS customer_count
-- FROM customer_shopping_behavior
-- GROUP BY customer_segment
-- ORDER BY customer_count DESC;

-- Q8. What are the top 3 most purchased products within each category?

WITH product_counts AS (
    SELECT
        `Category`,
        `Item Purchased`,
        COUNT(*) AS total_purchases,
        RANK() OVER (
            PARTITION BY `Category`
            ORDER BY COUNT(*) DESC
        ) AS product_rank
    FROM customer_shopping_behavior
    GROUP BY `Category`, `Item Purchased`
)

SELECT
    `Category`,
    `Item Purchased`,
    total_purchases
FROM product_counts
WHERE product_rank <= 3
ORDER BY `Category`, total_purchases DESC;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    `Subscription Status`,
    COUNT(*) AS customer_count
FROM customer_shopping_behavior
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;

-- SELECT
--     `Subscription Status`,
--     COUNT(*) AS customer_count,
--     ROUND(COUNT(*) * 100.0 / (
--         SELECT COUNT(*)
--         FROM customer_shopping_behavior
--         WHERE `Previous Purchases` > 5
--     ), 2) AS percentage
-- FROM customer_shopping_behavior
-- WHERE `Previous Purchases` > 5
-- GROUP BY `Subscription Status`;

-- Q10. What is the revenue contribution of each age group?

SELECT
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END AS age_group,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;

SELECT
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END AS age_group,
    SUM(`Purchase Amount (USD)`) AS total_revenue,
    ROUND(
        SUM(`Purchase Amount (USD)`) * 100.0 /
        (SELECT SUM(`Purchase Amount (USD)`)
         FROM customer_shopping_behavior),
        2
    ) AS revenue_percentage
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;


select * from customer_shopping_behavior;

